/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccountsModule"): TruffleContracts.AccountsModuleContract;
      require(name: "Base"): TruffleContracts.BaseContract;
      require(name: "BondingCurve"): TruffleContracts.BondingCurveContract;
      require(name: "CompoundModule"): TruffleContracts.CompoundModuleContract;
      require(name: "Context"): TruffleContracts.ContextContract;
      require(name: "CoreInterface"): TruffleContracts.CoreInterfaceContract;
      require(name: "Counter_V0"): TruffleContracts.Counter_V0Contract;
      require(name: "Counter_V1"): TruffleContracts.Counter_V1Contract;
      require(name: "Counter"): TruffleContracts.CounterContract;
      require(name: "CurveModule"): TruffleContracts.CurveModuleContract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "ERC20Burnable"): TruffleContracts.ERC20BurnableContract;
      require(name: "ERC20Detailed"): TruffleContracts.ERC20DetailedContract;
      require(name: "ERC20Mintable"): TruffleContracts.ERC20MintableContract;
      require(name: "Factory"): TruffleContracts.FactoryContract;
      require(name: "FundsModule"): TruffleContracts.FundsModuleContract;
      require(name: "ICurveModule"): TruffleContracts.ICurveModuleContract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "IFundsModule"): TruffleContracts.IFundsModuleContract;
      require(name: "MinterRole"): TruffleContracts.MinterRoleContract;
      require(name: "Module"): TruffleContracts.ModuleContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(name: "Pool"): TruffleContracts.PoolContract;
      require(name: "PoolFactory"): TruffleContracts.PoolFactoryContract;
      require(name: "PToken"): TruffleContracts.PTokenContract;
      require(
        name: "TestLiquidToken"
      ): TruffleContracts.TestLiquidTokenContract;
      require(name: "TestSQRT"): TruffleContracts.TestSQRTContract;
      require(name: "TokenModule"): TruffleContracts.TokenModuleContract;
      require(name: "VotesModule"): TruffleContracts.VotesModuleContract;
    }
  }
}
