/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccountsModule"): TruffleContracts.AccountsModuleContract;
      require(name: "Base"): TruffleContracts.BaseContract;
      require(name: "CompoundModule"): TruffleContracts.CompoundModuleContract;
      require(name: "Context"): TruffleContracts.ContextContract;
      require(name: "CoreInterface"): TruffleContracts.CoreInterfaceContract;
      require(name: "Counter_V0"): TruffleContracts.Counter_V0Contract;
      require(name: "Counter_V1"): TruffleContracts.Counter_V1Contract;
      require(name: "Counter"): TruffleContracts.CounterContract;
      require(name: "CurveModule"): TruffleContracts.CurveModuleContract;
      require(name: "Factory"): TruffleContracts.FactoryContract;
      require(name: "FundsModule"): TruffleContracts.FundsModuleContract;
      require(name: "IBondingCurve"): TruffleContracts.IBondingCurveContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(name: "Pool"): TruffleContracts.PoolContract;
      require(name: "PoolFactory"): TruffleContracts.PoolFactoryContract;
      require(name: "PToken"): TruffleContracts.PTokenContract;
      require(name: "TokenModule"): TruffleContracts.TokenModuleContract;
      require(name: "VotesModule"): TruffleContracts.VotesModuleContract;
    }
  }
}
