/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Counter_V0"): TruffleContracts.Counter_V0Contract;
      require(name: "Counter_V1"): TruffleContracts.Counter_V1Contract;
      require(name: "Counter"): TruffleContracts.CounterContract;
    }
  }
}
